# BetterMe DevOps Test - Outputs
# This file exposes important values from the infrastructure

# General Outputs
output "region" {
  description = "AWS region"
  value       = var.region
}

# VPC Outputs
output "vpc_id" {
  description = "ID of the VPC"
  value       = module.vpc.vpc_id
}

output "vpc_cidr_block" {
  description = "CIDR block of the VPC"
  value       = module.vpc.vpc_cidr_block
}

output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.vpc.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.vpc.public_subnets
}

# EKS Outputs
output "cluster_id" {
  description = "EKS cluster ID"
  value       = module.eks.cluster_id
}

output "cluster_name" {
  description = "EKS cluster name"
  value       = module.eks.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value       = module.eks.kubectl_config
  sensitive   = true
}

# RDS Outputs
output "db_instance_endpoint" {
  description = "RDS instance endpoint"
  value       = module.rds.db_endpoint
  sensitive   = true
}

output "db_instance_name" {
  description = "RDS instance name"
  value       = module.rds.db_name
}

output "db_name" {
  description = "Database name"
  value       = module.rds.db_name
}

output "db_username" {
  description = "Database username"
  value       = module.rds.db_username
  sensitive   = true
}

# S3 Outputs
output "public_s3_bucket_name" {
  description = "Name of the public S3 bucket"
  value       = module.s3.public_bucket_name
}

output "public_s3_bucket_url" {
  description = "URL of the public S3 bucket"
  value       = "https://${module.s3.public_bucket_name}.s3.amazonaws.com"
}

output "private_s3_bucket_name" {
  description = "Name of the private S3 bucket"
  value       = module.s3.private_bucket_name
}

output "private_s3_bucket_url" {
  description = "URL of the private S3 bucket"
  value       = "https://${module.s3.private_bucket_name}.s3.amazonaws.com"
}

