apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.project.name }}-ingress"
  namespace: "{{ .Values.project.name }}"

spec:
  rules:
    - host: "{{ .Values.ingress.domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ .Values.project.name }}-service"
                port:
                  number: 80